import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Impact Theory Test Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        NEXT_PUBLIC_API_URL = {process.env.NEXT_PUBLIC_API_URL || "Didn't get the env var"}
        </h1>

        <p className={styles.description}>
          Another one. NODE_REMOTE = {process.env.NODE_REMOTE || "Didn't get NODE_REMOTE :("}
        </p>

        <p className={styles.description}>
          Another one. NODE_ENV = {process.env.NODE_ENV || "Didn't get NODE_ENV :("}
        </p>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
