import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Impact Theory Test Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to {process.env.NEXT_PUBLIC_API_URL || "Didn't get the env var"}
        </h1>

        <p className={styles.description}>
          Another one. NEXT_PUBLIC_MY_VAR = {process.env.NEXT_PUBLIC_MY_VAR || "Didn't get MY_VAR :("}
        </p>

        <p className={styles.description}>
          Another one. NODE_ENV = {process.env.NODE_ENV || "Didn't get NODE_ENV :("}
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
